### ISSUE TITLE
Why keybinder works in Wayland using gtk2 but doesn't work using gtk3 gir bindings?

### ISSUE THREAD

**Issue by gornostal** [kupferlauncher/keybinder#11]
Hi there,
I've been using keybinder3 with gir bindings for a while. Now I'm looking for a way to make it work in Wayland session. After doing some research I found this:

[GTK3 + gir bindings](https://github.com/kupferlauncher/keybinder/blob/master/examples/example.py) - works in X session, doesn't work in Wayland
[GTK2 + python-keybinder lib](https://gist.github.com/anonymous/bcb42875ed2d98afb9e6afc87ce8a287) - works in X and Wayland session

Can someone explain this behavior please?

Thanks.

**Comment by TingPing** [comment]
Because Gtk2 applications are ran in XWayland. `env GDK_BACKEND=x11` would make a Gtk3 application run under XWayland too.

**Comment by gornostal** [comment]
Awesome. Now my app runs in Wayland

Thanks a lot @TingPing

**Comment by TingPing** [comment]
Just to state the obvious, forcing using X11 is of course not ideal.

**Comment by gornostal** [comment]
Yeah, you are right.
However there is no way to programmatically bind a hotkey in Wayland, is there?

**Comment by TingPing** [comment]
No. One one of doing it is exposing an action in your application and then the user can configure their compositor to call that action by keypress.

**Comment by gornostal** [comment]
Like a dbus method?
Could you please share a link where I can read more about how to do that the right way?

After discovering that there is no way of binding a hotkey using API I thought of making an executable that would call a dbus method of my app. But I think binding a hotkey to run a program may result in a noticeable delay :thinking:

**Comment by TingPing** [comment]
@gornostal

- Use GApplication: https://wiki.gnome.org/HowDoI/GtkApplication
- Add your GAction: https://wiki.gnome.org/HowDoI/GAction
- Call it over dbus

> But I think binding a hotkey to run a program may result in a noticeable delay

DBus IPC is technically slower yes but it isn't noteworthy.

**Comment by gornostal** [comment]
Thanks :)
