### ISSUE TITLE
How to build for GTK3?

### ISSUE THREAD

**Issue by HighCommander4** [kupferlauncher/keybinder#8]
How do I build this library for GTK3? Is there a configure option? With the default options it seems to only have built the GTK2 version of the library.

**Comment by HighCommander4** [comment]
Oh, you have to build from a different git branch!

You may want to mention this in the README, it's not at all obvious.

**Comment by bram209** [comment]
@HighCommander4  I agree, was searching for this as well

**Comment by bluss** [comment]
Fixed
